/* Riposte Laboratories — generated by scripts/build.js. Do not edit.
   Usage:  module.exports = { presets: [require('./brand/tailwind.preset.js')] }
   Radius is forced to 0 and shadows to hard offsets: the brand has no soft edges. */
module.exports = {
  theme: {
    extend: {
      colors: {
              "ink": "#1d1a17",
              "ink-raised": "#241f1b",
              "ink-head": "#2b2723",
              "ink-line": "#5c554c",
              "bone": "#f6f1e7",
              "bone-dim": "#eae4d6",
              "white": "#ffffff",
              "pink": "#f0477d",
              "orange": "#fe9a0d",
              "teal": "#12b795",
              "pink-deep": "#d81150",
              "orange-deep": "#a15e01",
              "teal-deep": "#0c7a63",
              "teal-ink": "#04463a"
      },
      fontFamily: { mono: ["JetBrains Mono", "IBM Plex Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Consolas", "Liberation Mono", "monospace"] },
      spacing: {
              "rl1": "4px",
              "rl2": "8px",
              "rl3": "12px",
              "rl4": "16px",
              "rl5": "24px",
              "rl6": "34px",
              "rl7": "48px",
              "rl8": "64px",
              "rl9": "72px"
      },
      maxWidth: { rl: '1060px', 'rl-wide': '1160px', 'rl-prose': '900px', measure: '66ch' },
      letterSpacing: {
              "display": "-.01em",
              "h": ".03em",
              "nav": ".08em",
              "label": ".1em",
              "tag": ".14em",
              "spec": ".16em",
              "kicker": ".3em",
              "wordmark": ".55em"
      },
      borderWidth: { rule: '2px', bar: '6px', barl: '8px' },
      boxShadow: {
        pop: '4px 4px 0 #f0477d',
        'pop-teal': '4px 4px 0 #12b795',
        stack: '8px 8px 0 #12b795, 16px 16px 0 #f0477d',
      },
      backgroundImage: {
        triband: 'linear-gradient(105deg, #f0477d 0 36%, #fe9a0d 36% 64%, #12b795 64% 100%)',
      },
      transitionDuration: { flick: '120ms', snap: '150ms', move: '250ms' },
    },
    borderRadius: { none: '0', DEFAULT: '0', sm: '0', md: '0', lg: '0', xl: '0', full: '0' },
  },
};
